//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeSerB.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class giderler
    {
        public int Odemeid { get; set; }
        public Nullable<int> Elektrik { get; set; }
        public Nullable<int> Su { get; set; }
        public Nullable<int> Dogalgaz { get; set; }
        public Nullable<int> internet { get; set; }
        public Nullable<int> Gida { get; set; }
        public Nullable<int> Personel { get; set; }
        public Nullable<int> Diger { get; set; }
        public Nullable<int> personelId { get; set; }
    
        public virtual personel personel1 { get; set; }
        public virtual Kasa Kasa { get; set; }
    }
}
