//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeSerB.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kasa
    {
        public string OdemeAy { get; set; }
        public Nullable<int> OdemeMiktar { get; set; }
        public int OdemeId { get; set; }
    
        public virtual giderler giderler { get; set; }
        public virtual ogrenci ogrenci { get; set; }
    }
}
