//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeSerB.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class projeEntities2 : DbContext
    {
        public projeEntities2()
            : base("name=projeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bolumler> bolumler { get; set; }
        public virtual DbSet<borclar> borclar { get; set; }
        public virtual DbSet<giderler> giderler { get; set; }
        public virtual DbSet<Kasa> Kasa { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<odalar> odalar { get; set; }
        public virtual DbSet<ogrenci> ogrenci { get; set; }
        public virtual DbSet<personel> personel { get; set; }
    
        public virtual ObjectResult<ogrenciGetir_Result> ogrenciGetir(string ogrenci)
        {
            var ogrenciParameter = ogrenci != null ?
                new ObjectParameter("ogrenci", ogrenci) :
                new ObjectParameter("ogrenci", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ogrenciGetir_Result>("ogrenciGetir", ogrenciParameter);
        }
    }
}
