//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeSerB.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ogrenci()
        {
            this.borclar = new HashSet<borclar>();
        }
    
        public int Ogrid { get; set; }
        public string OgrAd { get; set; }
        public string OgrSoyad { get; set; }
        public string OgrTc { get; set; }
        public string OgrTelefon { get; set; }
        public string OgrDogum { get; set; }
        public string OgrBolum { get; set; }
        public string OgrMail { get; set; }
        public string OgrOdaNo { get; set; }
        public string OgrVeliAdSoyad { get; set; }
        public string OgrVeliTelefon { get; set; }
        public string OgrVeliAdres { get; set; }
        public Nullable<int> OgrenciBolumid { get; set; }
        public Nullable<int> OgrOda { get; set; }
    
        public virtual bolumler bolumler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borclar> borclar { get; set; }
        public virtual Kasa Kasa { get; set; }
        public virtual odalar odalar { get; set; }
    }
}
